<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <description>Use to generate test class.</description>
    <label>Test Generator</label>
    <tab>Test_Generator</tab>
    <tab>Data_Change_Request__c</tab>
    <tab>Dummymaster__c</tab>
    <tab>Camping_Item__c</tab>
    <tab>Employee12__c</tab>
    <tab>NGEN_ExceptionRequest__c</tab>
    <tab>pocrecurrsive__c</tab>
    <tab>Parent__c</tab>
    <tab>ChildLookup__c</tab>
    <tab>ChildMasterDetail__c</tab>
    <tab>RecordTypeObject__c</tab>
    <tab>processbuilder__c</tab>
    <tab>Part_menu__c</tab>
    <tab>customer_order__c</tab>
    <tab>Bin__c</tab>
    <tab>Comments__c</tab>
    <tab>Sharing_Rule_obj__c</tab>
    <tab>Alphas__c</tab>
    <tab>A11__c</tab>
    <tab>B11__c</tab>
    <tab>JunObj__c</tab>
    <tab>Recurrsive_Obj__c</tab>
    <tab>Dobut__c</tab>
    <tab>ParentTrigger__c</tab>
    <tab>ChildTrigger__c</tab>
    <tab>M1__c</tab>
    <tab>M2__c</tab>
    <tab>M3__c</tab>
    <tab>M4__c</tab>
    <tab>M5__c</tab>
    <tab>M6__c</tab>
    <tab>M7__c</tab>
    <tab>UserChild__c</tab>
    <tab>System_Validation__c</tab>
    <tab>VF__c</tab>
    <tab>M11__c</tab>
    <tab>Recordtype__c</tab>
    <tab>Full_Access__c</tab>
    <tab>ParentObj__c</tab>
    <tab>Childobj__c</tab>
    <tab>PB__c</tab>
    <tab>Private__c</tab>
    <tab>ParentObj2__c</tab>
    <tab>Rollup_Parent__c</tab>
    <tab>Rollup_Child__c</tab>
    <tab>Mixed_DML_Ex__c</tab>
    <tab>MasterD__c</tab>
    <tab>ChildD__c</tab>
    <tab>Queueable__c</tab>
    <tab>Master1__c</tab>
    <tab>Master2__c</tab>
    <tab>JunctionObj__c</tab>
    <tab>Account__c</tab>
    <tab>RelationShipAccount__c</tab>
</CustomApplication>
